/* tslint:disable */
/* eslint-disable */
/**
 * Swagger
 * This is a sample server
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Model,
    ModelFromJSON,
    ModelFromJSONTyped,
    ModelToJSON,
} from './';

/**
 * 
 * @export
 * @interface DynamicModel
 */
export interface DynamicModel {
    /**
     * To update the dynamic model
     * @type {string}
     * @memberof DynamicModel
     */
    documentId?: string;
    /**
     * 
     * @type {string}
     * @memberof DynamicModel
     */
    document: string;
    /**
     * 
     * @type {Model}
     * @memberof DynamicModel
     */
    model: Model;
}

export function DynamicModelFromJSON(json: any): DynamicModel {
    return DynamicModelFromJSONTyped(json, false);
}

export function DynamicModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): DynamicModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'documentId': !exists(json, 'documentId') ? undefined : json['documentId'],
        'document': json['document'],
        'model': ModelFromJSON(json['model']),
    };
}

export function DynamicModelToJSON(value?: DynamicModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'documentId': value.documentId,
        'document': value.document,
        'model': ModelToJSON(value.model),
    };
}


