/* tslint:disable */
/* eslint-disable */
/**
 * Swagger
 * This is a sample server
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Property,
    PropertyFromJSON,
    PropertyFromJSONTyped,
    PropertyToJSON,
} from './';

/**
 * 
 * @export
 * @interface DynamicDataRequestModel
 */
export interface DynamicDataRequestModel {
    /**
     * To update the dynamic model
     * @type {string}
     * @memberof DynamicDataRequestModel
     */
    documentId?: string;
    /**
     * 
     * @type {Property}
     * @memberof DynamicDataRequestModel
     */
    requestModel?: Property;
}

export function DynamicDataRequestModelFromJSON(json: any): DynamicDataRequestModel {
    return DynamicDataRequestModelFromJSONTyped(json, false);
}

export function DynamicDataRequestModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): DynamicDataRequestModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'documentId': !exists(json, 'documentId') ? undefined : json['documentId'],
        'requestModel': !exists(json, 'requestModel') ? undefined : PropertyFromJSON(json['requestModel']),
    };
}

export function DynamicDataRequestModelToJSON(value?: DynamicDataRequestModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'documentId': value.documentId,
        'requestModel': PropertyToJSON(value.requestModel),
    };
}


